<?php

namespace Hmp\KumaExtraBundle\Repository;

/**
 * GlobalValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalValueRepository extends \Doctrine\ORM\EntityRepository
{
}
